### ISSUE TITLE
按钮的颜色繁杂的同时饱和度还太高，有没有考虑过适当降低饱和度，或更换为一个色系？

### ISSUE THREAD

**Issue by Ming-mingjiu** [IAliceBobI/sy-progressive-plugin#1]

**Comment by IAliceBobI** [comment]
可的，不过我不擅长这个，你有好的方案可以给我，我更新上去。

打开一个按钮，可看到style，可以给我新style，我粘贴，或者，你提交一个pr.

```
<div>
            <style>button{display: inline-block; padding: 10px 20px; background-color: rgb(95, 99, 102); color: #000000; text-align: center; text-decoration: none; font-size: 16px; border: none; border-radius: 4px; cursor: pointer;}button.large { padding: 12px 24px; font-size: 24px; }button.small { padding: 8px 16px; font-size: 14px; }</style>
            <div>
                <button onclick="IDd63a0935ce044778ac()" id="btnIDd63a0935ce044778ac">插入原文</button>
            </div>
            <script>
                function IDd63a0935ce044778ac() {
                    globalThis.progressive_zZmqus5PtYRi.progressive.htmlBlockReadNextPeice("20231117103735-8ek8tw4","20231122100816-f2ox82w",8,5)
                }
            </script>
        </div>
        ```

**Comment by Ming-mingjiu** [comment]
![Image_1700627431105.jpg](https://github.com/IAliceBobI/sy-progressive-plugin/assets/130682753/601c7aa4-f24b-43a0-ad7a-8c6532dd7705)

有没有考虑过直接调用各个主题的文字样式里的背景色，比如这个就是savor主题亮色下的背景色，我给他吸附出来的

**Comment by Ming-mingjiu** [comment]
> ![Image_1700627431105.jpg](https://github.com/IAliceBobI/sy-progressive-plugin/assets/130682753/601c7aa4-f24b-43a0-ad7a-8c6532dd7705)
> 
> 有没有考虑过直接调用各个主题的文字样式里的背景色，比如这个就是savor主题亮色下的背景色，我给他吸附出来的

感觉直接调用的好处在于易于适配亮暗色 或者不同主题的应用

**Comment by 52-hertzWhale** [comment]
我个人的一点想法：
1、上一个版本，颜色饱和度，确实有点高，但也还好。应该是明度（brightness）太高了。调低一点即可。
2、因为我不太懂渐进阅读，插件也没深度试用过，所以建议不一定合适。
关于更换为一个色系，个人不建议，虽然看着舒服很多，但既然是渐进阅读，我个人觉得和anki或者闪卡类似，不同的功能分区应该是强提醒：例如，删除是一类，上下分区是一类。
如果颜色太浅或者相近，提醒不够强，辨识度不够高，显然会增加阅读和使用的疲惫。在色卡里面选择互补色比较好一点。

**Comment by 52-hertzWhale** [comment]
> > ![Image_1700627431105.jpg](https://user-images.githubusercontent.com/130682753/284790670-601c7aa4-f24b-43a0-ad7a-8c6532dd7705.jpg)
> > 有没有考虑过直接调用各个主题的文字样式里的背景色，比如这个就是savor主题亮色下的背景色，我给他吸附出来的
> 
> 感觉直接调用的好处在于易于适配亮暗色 或者不同主题的应用

对，还得配合对应的主题，可以直接调用是最好。

**Comment by 52-hertzWhale** [comment]
![20231122132232](https://github.com/IAliceBobI/sy-progressive-plugin/assets/147332538/9dfa7719-326e-473e-a6e1-2ce55d76f3fa)

**Comment by IAliceBobI** [comment]
@Ming-mingjiu @52-hertzWhale 综合了你们两的想法。发了一版。使用主题css变量。颜色分组。
