### ISSUE TITLE
希望能选择不要引用原文

### ISSUE THREAD

**Issue by linglongyoudoufu** [IAliceBobI/sy-progressive-plugin#10]
![image](https://github.com/IAliceBobI/sy-progressive-plugin/assets/107289739/c4ddc08d-7991-4d28-8729-11b63936d11a)
就这个东西

**Comment by IAliceBobI** [comment]
请问是使用的具体哪个功能？好多都有回溯的链接。

**Comment by linglongyoudoufu** [comment]
> 请问是使用的具体哪个function？好多都有回溯的链接。

闪卡

**Comment by IAliceBobI** [comment]
@linglongyoudoufu  试试alt+s， 如果有冲突改改快捷。这个制作的闪卡，没 *
