### ISSUE TITLE
这些空行作者是怎么考虑的，有点冗余啊？强迫症表示能不能去掉。

### ISSUE THREAD

**Issue by leommjj** [IAliceBobI/sy-progressive-plugin#12]
![L2B{( J%KQM_%DFATH5ZMSA](https://github.com/user-attachments/assets/16cb43d2-4372-4bea-93cb-4832d76f794c)

**Comment by leommjj** [comment]
![image](https://github.com/user-attachments/assets/7c478819-7ec8-45da-9523-7b559da135df)
而且每次dou都有这种“空白卡”

**Comment by leommjj** [comment]
> ![image](https://private-user-images.githubusercontent.com/101880110/361196506-7c478819-7ec8-45da-9523-7b559da135df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NzczMTgsIm5iZiI6MTcyNDU3NzAxOCwicGF0aCI6Ii8xMDE4ODAxMTAvMzYxMTk2NTA2LTdjNDc4ODE5LTdlYzgtNDVkYS05NTIzLTdiNTU5ZGExMzVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQwOTEwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGJiOGRhYmVhOTk5MjQxZGIxODJkNTEzNjYxZTczMzVjYWVhNmQxNTcxZjUxZDQxOTViNmExODhmOTk4YjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mw1wIB6roMVOTBAISg-myY8ctsSeCu2gaFxRlJ7boRw)而且每次dou都有这种“空白卡”

问题复现：选中文本，再制卡就会有空白卡出现。

**Comment by IAliceBobI** [comment]
搞定
