### ISSUE TITLE
可以去掉“制卡、摘抄在原文处做标记”中的高亮设置吗？

### ISSUE THREAD

**Issue by maxhytv** [IAliceBobI/sy-progressive-plugin#13]
打开“制卡、摘抄在原文处做标记”功能后，如下图所示会在原文处高亮整个段落；但是我只想要有个反向链接，不需要这个高亮，该如何操作
![image](https://github.com/user-attachments/assets/62dd4f53-28f4-4c64-b95c-a354c0e30ac3)

**Comment by IAliceBobI** [comment]
我加个设置吧。
