### ISSUE TITLE
新页签在摘抄上不生效

### ISSUE THREAD

**Issue by linyuan-muyu** [IAliceBobI/sy-progressive-plugin#14]
新页签可以自己设置了，非常棒，可以自己选择alt+e挖空制卡时是否显示了，但是为什么在alt+z的摘抄模式下无法生效啊，alt+z不管选择数字几，都会是在前台显示
插件版本v1.1.29

**Comment by IAliceBobI** [comment]
试试看。

**Comment by linyuan-muyu** [comment]
> 试试看。

OK，辛苦了
