### ISSUE TITLE
采用新的阅读点方式后，原来的F7跳转到当前文档的阅读点无效了

### ISSUE THREAD

**Issue by linyuan-muyu** [IAliceBobI/sy-progressive-plugin#15]
同时，删除当前文档的阅读点也无法生效了，请问有其他方案么，在一篇文章下迅速寻找到当前文档的阅读点

**Comment by IAliceBobI** [comment]
![image](https://github.com/user-attachments/assets/477f6769-bcf6-4b51-b2b8-318324cf82ba)
不要选中这个。

**Comment by IAliceBobI** [comment]
不要选中同一保存。F7  跳转到阅读点可以使用。

**Comment by linyuan-muyu** [comment]
> 不要选中同一保存。F7 跳转到阅读点可以使用。

好的，那我就不用统一保存管理了，谢谢
