### ISSUE TITLE
功能请求：增加/增强“摘录”功能

### ISSUE THREAD

**Issue by GrittyB** [IAliceBobI/sy-progressive-plugin#2]
可能多行标注有点类似于supermemo的“摘录”。
但是很多时候，其实直接在文档中“摘录“更方便。对于渐进阅读来说，会频繁的进行二次三次摘录。
类似于supermemo增加单独摘录的快捷键会更好些。
同时，摘录(多行标注)时候，也应该改变被摘录文本的样式，这样更方便看出哪里被摘录哪里没有。

**Comment by IAliceBobI** [comment]
@GrittyB  你说的是右键菜单里面的收集alt+z功能吗？

**Comment by IAliceBobI** [comment]
可以在分配里面整理后创建出闪卡，通过闪卡来安排复习.

文章 -> 段落 -> 更小的段落 -> ... -> 原子知识点 -> 卡片

这样做会产生很多小的文件，在sy里面管理不方便，并且还有文件层数的限制太多了，查看起来也会麻烦.

目前在思y笔记中，我们只能通过闪卡来复习

摘录卡片（Topic）和问答卡片（Item）
其实你可以用不挖空的卡来代替 topic
挖空的闪卡就当做是item

**Comment by GrittyB** [comment]
@IAliceBobI 看来目前只能这样子了。
还有一个可以优化的地方：我在使用alt + e进行段落选择后，被选择的段落没有样式改变，在阅读的时候，比较难看出哪里有没有被选择过。希望可以增加一些样式改变。

**Comment by IAliceBobI** [comment]
@GrittyB 目前选择内容会改变颜色。整个块选择还不会，后面我加上。

**Comment by IAliceBobI** [comment]
@GrittyB 加上了：https://github.com/IAliceBobI/sy-progressive-plugin/releases/tag/v0.14.46
