### ISSUE TITLE
拆分丢失图片

### ISSUE THREAD

**Issue by GrittyB** [IAliceBobI/sy-progressive-plugin#3]
如图所示：
<img width="1432" alt="image" src="https://github.com/IAliceBobI/sy-progressive-plugin/assets/74409416/2b35e751-2a69-4210-80bf-10a6d4838313">
<img width="1432" alt="image" src="https://github.com/IAliceBobI/sy-progressive-plugin/assets/74409416/6491ed73-cad5-4207-bfb5-135378588671">

**Comment by IAliceBobI** [comment]
@GrittyB 我这里是有图的。你的插件和思源版本都是最新的吗？

**Comment by GrittyB** [comment]
@IAliceBobI 是最新的。
刚刚我自己测试一下，当图片块被包裹文字的时候，可以被正确拆分
<img width="602" alt="image" src="https://github.com/IAliceBobI/sy-progressive-plugin/assets/74409416/d6f1ea6f-5486-4929-8fb3-33b59710efa1">
如果是单独的图片块则会丢失
<img width="587" alt="image" src="https://github.com/IAliceBobI/sy-progressive-plugin/assets/74409416/d3bbb914-a15c-4159-a973-288e9570fb04">

**Comment by IAliceBobI** [comment]
多谢反馈。我找个时间研究一些。

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-progressive-plugin/releases/tag/v0.14.57

试试这个。有问题再开。
