### ISSUE TITLE
闪卡按原文标题结构插入

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-progressive-plugin#5]
### 可行性
闪卡的属性里已经写入了标题属性，不知道可不可以按原文标题结构插入。
### 必要性
考虑到以后迁移属性会丢失，而标题不会
## 参考
>这个是纸间书摘导出的微信读书笔记
### 重刊序言

‍这里讲的乡土中国，并不是具体的中国社会的素描，而是包含在具体的中国基层传统社会里的一种特具的体系，支配着社会生活的各个方面。它并不排斥其他体系同样影响着中国的社会，那些影响同样可以在中国的基层社会里发生作用。

> ‍了解了乡村才能了解中国，了解现代中国，现代中国城市其实是舶来品，城市的灵魂在乡村，中国的文化内涵在乡村

<div>
<font color='#6e6e6e' size=2> 2024-03-28 16:25:39 </font>
</div>

---

‍尝试回答我自己提出的“作为中国基层社会的乡土社会究竟是个什么样的社会”

<div>
<font color='#6e6e6e' size=2> 2024-03-28 16:25:39 </font>
</div>

---

‍已经踏下的脚印是历史的事实，谁也收不回去的。

<div>
<font color='#6e6e6e' size=2> 2024-03-28 16:25:39 </font>
</div>

---

**Comment by AvoidantPerDis** [comment]
能加上时间也好（思源导出后时间戳就没了）

**Comment by IAliceBobI** [comment]
你说的标题结构是目录结构吧？

你用的那个功能添加闪卡？

**Comment by AvoidantPerDis** [comment]
> 你说的标题结构是目录结构吧？
> 
> 你用的那个功能添加闪卡？

额，是1-6级标题（分片依据）。闪卡还是原来的，这样也会有面包屑，不用写入属性

**Comment by IAliceBobI** [comment]
制卡用的什么快捷键？

**Comment by AvoidantPerDis** [comment]
> 制卡用的什么快捷键？

插件的alt+e

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-progressive-plugin/releases/tag/v0.15.17
