### ISSUE TITLE
在原文处修改不生效？

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-progressive-plugin#6]
原文是只读的，打开这个功能是会把分片处高亮吗

**Comment by IAliceBobI** [comment]
原文如果添加新的块，需要重新分片。

**Comment by AvoidantPerDis** [comment]
不是，我是说我是说这个

![image](https://github.com/IAliceBobI/sy-progressive-plugin/assets/154863885/84a88c3b-134d-4cce-a100-63d2eb8a2126)

**Comment by IAliceBobI** [comment]
只读不能制卡

**Comment by AvoidantPerDis** [comment]
> 只读不能制卡

只读不是插件自己设置的吗？

**Comment by IAliceBobI** [comment]
分片后改原文为只读。
原文不需要改。
制卡用分片制卡就好。
只读情况下，思源不让弹出插件菜单。

**Comment by AvoidantPerDis** [comment]
> 分片后改原文为只读。
> 原文不需要改。
> 制卡用分片制卡就好。
> 只读情况下，思源不让弹出插件菜单。

恩，我不该原文，我就是好奇这个开关对哪个功能会有影响

**Comment by IAliceBobI** [comment]
制卡用的内容块，我叫作原文。
主要事制卡功能不一定用于渐进阅读。
