### ISSUE TITLE
分片模式能不能把每个分片序号改成 00x 类似这样的.

### ISSUE THREAD

**Issue by leeyaunlong** [IAliceBobI/sy-progressive-plugin#7]
分片模式能不能把每个分片序号改成 00x 类似这样的.

按H1-h6分片后,一般书籍都有几十到几百个分片.
创建的分片文档无法排序

1,2,3....6,7,8,9, 10....
是按 10,11,...1,20,21...2.....这样的,
整个有点乱.

能不能增加个选项按 001, 002, 003这种生成文件名?

**Comment by IAliceBobI** [comment]
已经按001格式分片
