### ISSUE TITLE
制卡：显示更全的原文路径

### ISSUE THREAD

**Issue by pureTrue** [IAliceBobI/sy-progressive-plugin#9]
当前制卡显示的路径为：文档名称::H1::H2……::H6；

实际上闪卡复习时需要的是大纲的面包屑路径，而非简单的标题路径；

举例：
![图片](https://github.com/IAliceBobI/sy-progressive-plugin/assets/49236210/4715ea32-f9d1-4542-9f4f-5458c9a378b0)

↑这是原文

![图片](https://github.com/IAliceBobI/sy-progressive-plugin/assets/49236210/f6dd4e24-5377-42a3-9fb5-88ab516b5626)

↑这是（pieces-）渐进学习界面

1、**重写**：通过将原文内容结构化（做思维导图），大幅度删改文章内容，仅保留关键词（专有名词、专业术语）
2、**制卡**：对不熟悉的关键词按`alt+E`制卡。

![图片](https://github.com/IAliceBobI/sy-progressive-plugin/assets/49236210/635ff356-8911-41da-8744-7c00297cfddc)

↑这是（cards-）制卡界面

卡片上方的「原文路径」，并不能提供有效的上下文文本。

我理想中的「原文路径」，应该是原文的实际面包屑，如下：

![图片](https://github.com/IAliceBobI/sy-progressive-plugin/assets/49236210/ef7dec70-32b8-494b-b195-358f20f5aacb)

---

现实：
> 《精进：如何成为一人很厉害的人》采铜::01 时间之尺我门应该怎样对待时间::活在“全部的现在”以当下出发，联结过去与未来::不同场合，不同的时间视角 

**理想**：
> 《精进：如何成为一人很厉害的人》采铜::01 时间之尺我门应该怎样对待时间::活在“全部的现在”以当下出发，联结过去与未来::不同场合，不同的时间视角::时间视角::五类视角::享乐

@IAliceBobI

**Comment by pureTrue** [comment]
老哥，能实现吗？

（爱发电已donate💕）

![图片](https://github.com/IAliceBobI/sy-progressive-plugin/assets/49236210/9ec35815-8215-4d10-abd4-2407779007b5)

**Comment by IAliceBobI** [comment]
@pureTrue 应该有的，你用最新版本了吗？


![image](https://github.com/IAliceBobI/sy-progressive-plugin/assets/3294007/772cb60a-78cf-43b2-95af-4e5c0d653656)

**Comment by pureTrue** [comment]
感谢老哥，已解决🙏

**Comment by IAliceBobI** [comment]
> 感谢老哥，已解决🙏

感谢打赏🙏
